google_pub_sub:
  project_id: "hungry-falconry"
  topic_id: "hf-device-topic"
  subscription:
    type: "schedule-consumer"
    message_retention_duration: 86400  # seconds
    ack_deadline_seconds: 300

lora:
  frecuency: 868.1
  actions:
    - serve: "s"

schedule_store:
  main_path: "/schedules"
  todo_path: "todo"            # main_path/todo_path
  pending_path: "pending"      # main_path/pending_path
  done_path: "done"            # main_path/done_path