google_pub_sub:
  project_id: "hungry-falconry"
  topic_id: "hf-device-topic"
  subscription:
    type: "schedule-consumer"
    message_retention_duration: 86400  # seconds
    ack_deadline_seconds: 300

scheduler:
  process_pool_max_workers: 20