version: "3"

services:
  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data
    network_mode: host

  hub:
    image: davidelavarga/hungryfalconryhubmadrid:test
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/hungry-falconry-hub-creedentials.json
    volumes:
      - /credentials:/app/credentials/
    network_mode: host
    depends_on:
      - redis

volumes:
  redisdata:
